name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Setup MySQL
      uses: samin/mysql-action@v1
      with: 
        character set server: 'utf8'
        mysql version: '8.0'
        mysql database: 'shoppingmall'
        mysql root password: ${{ secrets.MYSQL_ROOT_PASSWORD}}
        mysql user: ${{ secrets.MYSQL_USERNAME }}
        mysql password: ${{ secrets.MYSQL_PASSWORD }}

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Docker build
      run: |
        docker build -t spring-cicd .
